server:
  port: 9000

spring:
  application:
    name: ad-getway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka

zuul:
  prefix: /lbw
  routes:
    sponsor:
      path: /ad-sponsor/**
      serviceId: eureka-client-ad-sponsor
      # 不过滤/ad-sponsor/**前缀
      strip-prefix: false